### ISSUE TITLE
emq_auth_http plugin does not check with the auth_server when publishing/subscribing messages

### ISSUE THREAD

**Issue by workingegg** [emqtt/emq-auth-http#12]
System info:

docker version: 1.12.5
emqtt version: emqttd-docker-v2.0.5
auth_server: running with nodejs http server on another docker
mqtt client: paho-mqtt-javascript 

Issue description:
Both emqtt server and auth server are on, and both of them can ping each other.
I am trying to authenticate connection and topic access control with emq_auth_http plugin.

According to the result, emqtt does check the connection with the auth server through emq_auth_http plugin, however, when client tries to publish the message, emqtt server DOES NOT check with the auth server through the plugin and instantly allows the client to publish the message.

Is this a known issue on this plugin, or I need to do other settings to enable ACL through this plugin?

**Comment by StarpTech** [comment]
I also have the same issue that the `/mqtt/acl` won't be called.

**Comment by StarpTech** [comment]
@workingegg you have to uncomment the superuser settings in the `emq_auth_http.conf`. After that a request against /acl is doing.

**Comment by huangdan** [comment]
@workingegg 
The superuser DOES NOT check ACL.

**Comment by chimit** [comment]
@huangdan there is a bug with ACL. ACL endpoint **is not called** for non-superuser and **is called** for superuser. Obviously, it should be vice versa.

I think there is the same problem described here:
https://github.com/emqtt/emqttd/issues/888
https://github.com/emqtt/emq-auth-http/issues/15

P.S. It would be better to close similar issues and leave only one.
