### ISSUE TITLE
For auth, 401 status still let the client connect

### ISSUE THREAD

**Issue by vishr** [emqtt/emq-auth-http#32]
In v2.2-beta.2 for auth I am returning 401 for invalid credentials but the client is still able to connect. As far I remember it was working in the earlier version of the plugin.

Also, for `auth.http.acl_nomatch = deny` it says invalid option but the docs refer to it http://emqtt.io/docs/v2/plugins.html#emq-auth-http-http-auth-acl-plugin.

Let me know if you need any information.

**Comment by vishr** [comment]
Do you accept it as a bug? I am not able to understand the label `support`.

**Comment by turtleDeng** [comment]
@vishr This bug will be released in next official version.

**Comment by vishr** [comment]
@turtleDeng Thanks for the update

**Comment by emqplus** [comment]
@vishr Fixed in 2.2-rc.1 release.

**Comment by vishr** [comment]
@emqplus Appreciate your effort.
