### ISSUE TITLE
No query params in http requests

### ISSUE THREAD

**Issue by dreamcatcha** [emqtt/emq-auth-http#46]
I created a nodejs app to service the requests of the http plugin but I'm not get any of the variables in a query string or request body...

Using the latest emqtt deb version server and the config file is correct as the node app gets the request but without any params, what am I doing wrong?

EDIT:

Helps when you have body parser setup correctly in your node app...

**Comment by sudhamab** [comment]
Hi, strangely we seem to be getting this issue as well and the bodyParser seems to be defined correctly as below but we are not getting any variables in the request body. Anything else we could be missing? 

import { Router } from 'express';
import bodyParser from 'body-parser';
const router = new Router();
router.use(bodyParser.json({ limit: '20mb' }));
router.use(bodyParser.urlencoded({ limit: '20mb', extended: true }));

**Comment by sudhamab** [comment]
@dreamcatcha would you be able to help with this one?

**Comment by dreamcatcha** [comment]
I have:

const app 	= express(),
	  router    = express.Router(),
	  server 	= http.createServer(app);

app.use(bodyParser.json({ limit: '10mb' }));
app.use(bodyParser.urlencoded({ limit: '10mb', extended: true }));
app.use('/', router);

router.use(function(req, res, next) {
    // your stuff
});

router.route('/mqtt/acl').get(<your route details>);
router.route('/mqtt/auth').post(<your route details>);
router.route('/mqtt/superuser').post(<your route details>);

server.listen(3000, function() {
      // Server running
});

and it works fine
